import {
  ArrowLeftOutline,
  CheckCircleOutline,
  EnvironmentOutline,
  FilterOutline,
  FlagOutline,
  LinkOutline,
  LoadingOutline,
  LogoutOutline,
  PlusCircleOutline,
  SearchOutline,
  SettingOutline,
  ShopOutline,
  SortAscendingOutline,
  StarOutline,
  UserOutline,
} from '@ant-design/icons-angular/icons';

export const icons = [
  SearchOutline,
  ArrowLeftOutline,
  EnvironmentOutline,
  LoadingOutline,
  CheckCircleOutline,
  ShopOutline,
  SettingOutline,
  UserOutline,
  LinkOutline,
  StarOutline,
  LogoutOutline,
  FilterOutline,
  SortAscendingOutline,
  PlusCircleOutline,
  FlagOutline,
];
