# Povinná atribuce ODbL/CC BY-SA (docs/soukromi.md, docs/lokalizace.md) — uvozující slovo
# ("Zdroj:"/"Foto:") se lokalizuje, jméno licence a zdroje ("Open Food Facts", "OpenStreetMap
# contributors", "CC BY-SA 4.0", "ODbL") je právní text a NEPŘEKLÁDÁ se v žádném jazyce.
attribution.media=Foto: přispěvatelé Kvalita a cena, licence CC BY-SA 4.0
attribution.off=Zdroj: Open Food Facts, licence ODbL
attribution.osm=Zdroj: © OpenStreetMap contributors, licence ODbL
attribution.cnb=Zdroj kurzu: Česká národní banka
